/* tslint:disable */
/* eslint-disable */

/* auto-generated by NAPI-RS */

export function sum(a: number, b: number): number
export class Oogway {
  constructor()
  set modelName(modelName: string)
}
